"""empty message

Revision ID: 8d897aef1066
Revises: 27483a7261f3
Create Date: 2021-10-25 20:04:32.248739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d897aef1066'
down_revision = '27483a7261f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('idade', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'idade')
    # ### end Alembic commands ###
