"""empty message

Revision ID: c93d01dd14f6
Revises: 8d897aef1066
Create Date: 2021-10-25 20:05:21.356295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c93d01dd14f6'
down_revision = '8d897aef1066'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'idade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('idade', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
