"""empty message

Revision ID: f18a1acf1c2c
Revises: 9d7292190115
Create Date: 2021-10-25 20:40:12.013345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f18a1acf1c2c'
down_revision = '9d7292190115'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enderecos', sa.Column('usuario_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'enderecos', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'enderecos', type_='foreignkey')
    op.drop_column('enderecos', 'usuario_id')
    # ### end Alembic commands ###
